server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: rakeshkeycloakpractice
  auth-server-url: http://localhost:8080
  resource: myclient
  public-client: true
  bearer-only: true